### ISSUE TITLE
requiredAddons in magwells component

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad_compat#1]
https://github.com/gruppe-adler/grad_compat/blob/5befaf0b01a0dda7e15305190175a515d232119e/addons/magWell/config.cpp#L9

Needs to be `grad_compat_main` right? Also this should contain the relevant GM and NIArms components to ensure correct load order.

**Comment by Salbei2500** [comment]
Good point will fix

**Comment by McDiod** [comment]
> Needs to be grad_compat_main right? 

No?

**Comment by Salbei2500** [comment]
no, why make a dependencie in a other addon?

**Comment by McDiod** [comment]
What I'm saying is, you have `grad_main` in your `requiredAddons`. `grad_main` is the main component of gruppe_adler_mod. This mod's main component is called `grad_compat_main`.

https://github.com/gruppe-adler/grad_compat/blob/784dca5a008dbdab269b7d14b6aafbc3c1e814d3/addons/magWell/config.cpp#L9

**Comment by Salbei2500** [comment]
ah, well your right
